import ReduxProvider from "@/redux/provider";
import StyledComponentsRegistry from "@/registry";
import ThemeRegistry from "@/theme/ThemeRegistry";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <ThemeRegistry>
          <body>
            <ReduxProvider>{children}</ReduxProvider>
          </body>
        </ThemeRegistry>
      </StyledComponentsRegistry>
    </html>
  );
}
